services:
  - type: web
    name: blitzapp
    env: node
    plan: starter
    buildCommand: yarn --frozen-lockfile --prod=false; blitz db migrate; blitz build
    # If you have an out of memory error, change startCommand to "yarn next start"
    startCommand: blitz start --production
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: bright
          property: "postgres://bright_user:to0X5jP7vA951E0vKvn9XFMo3vPoyhbK@dpg-bu53a58ti7j10msb6oeg/bright"
databases:
  - name: bright
    plan: starter
